// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Payment.Infrastructure;

namespace Payment.Infrastructure.Migrations
{
    [DbContext(typeof(TransactionDbContext))]
    [Migration("20220325121528_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Transaction")
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Payment.Domain.Model.Transaction.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnName("Amount")
                        .HasColumnType("decimal");

                    b.Property<int>("CVV")
                        .HasColumnName("CVV")
                        .HasColumnType("int");

                    b.Property<string>("CardholderNumber")
                        .IsRequired()
                        .HasColumnName("CardholderNumber")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnName("CreatedOn")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnName("Currency")
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("DeletedOn")
                        .HasColumnName("DeletedOn")
                        .HasColumnType("smalldatetime");

                    b.Property<byte>("ExpirationMonth")
                        .HasColumnName("ExpirationMonth")
                        .HasColumnType("tinyint");

                    b.Property<byte>("ExpirationYear")
                        .HasColumnName("ExpirationYear")
                        .HasColumnType("tinyint");

                    b.Property<string>("HolderName")
                        .IsRequired()
                        .HasColumnName("HolderName")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OrderReference")
                        .IsRequired()
                        .HasColumnName("OrderReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Status")
                        .HasColumnName("TransactionStatus")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("Uid")
                        .HasColumnName("UID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("tblTransactions","Transaction");
                });
#pragma warning restore 612, 618
        }
    }
}
